Feat: 강좌검색기능#4
ayu-capston/Senior-Job-Server pull request #6
Opened 2023-05-17 12:19 UTC by JunRyeol98

## **💡 Issue**

(PR | ISSUE) : #{PR | ISSUE 번호} 

## **⚡ Content**
title을 기준으로 검색기능 만들기

Controller
- 매핑함수 search() 추가
Service 
- searchPost() 추가 Repository에서 검색 결과를 받아와 비즈니스 로직을 실행하는 함수
- converEntityToDto() 함수 추가 Entity를 Dto로 변환하는 함수
Repository 
- findByTitleContaining()​ 추가 검색을 직접적으로 호출하는 함수

## **📆 TBD**
Controller - 페이징
-   페이징 만들기
- 기존에 존재한 컨트롤러의 list() 수정
- page 이름으로 넘어오는 파라미터를 받고 없으면 1로 설정하는 request 추가
Service - 페이징
- 기존에 존재했던 getLecturelist() 수정
## **🌟 Point**

-   검색 기능 추가

## ❓ Question

-   질문 사항이 있을 경우 적어주세요.

2023-05-17 12:22 UTC, designAR approved these changes
고생하셨어요~

2023-05-17 12:22 UTC, designAR commented on src/main/java/com/seniorjob/seniorjobserver/controller/LectureController.java
> +	}
dto변경후 검색기능 수정부탁드려요~

2023-05-17 12:22 UTC, designAR commented on src/main/java/com/seniorjob/seniorjobserver/service/LectureService.java
>  }
제안기능 merge후 dto변경!

2023-05-18 02:11 UTC, olive-su commented on src/main/java/com/seniorjob/seniorjobserver/controller/LectureController.java
> +	@GetMapping("/board/search")
End Point에는 uri를 기준으로 `method` 방식에 따라 구분하면 더 좋을 것 같습니다!

2023-05-18 02:18 UTC, olive-su requested changes
테스트용으로 view 작성하신거겠죠?
기능 개발 단위에서는 data만 response로 내려주시면 좋을 것 같아요..😭

<br>

제가 못 찾아서 그런지 모르겠는데,, 혹시 API 명세 관련해서는 따로 작성해놓으신게 있나요..?

<br>

**⭐️ Key 파일 올라갔습니다... ⭐️**
확인 후 커밋 내역 reset 후 다시 업로드 부탁드려요

2023-05-18 06:49 UTC, closed without merging